jobs:
  include:
    - name: deploy_draft
      if: branch = master
      language: node_js
      node_js:
        - lts/*
      script:
        - npm run test-and-build
      deploy:
        provider: pages
        fqdn: handlebars-draft.knappi.org
        skip-cleanup: true
        local_dir: target
        github-token: $GITHUB_TOKEN
        target_branch: gh-pages
        keep-history: true
        on:
          branch: master
    - name: deploy_draft
      if: branch = production
      language: node_js
      node_js:
        - lts/*
      script:
        - npm run test-and-build
      deploy:
        provider: pages
        fqdn: handlebars-prod.knappi.org
        repo: handlebars-lang/docs-prod-ghpages
        target-branch: master
        skip-cleanup: true
        local_dir: target
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: production

